#Fire will float you upward.
ascendingWinds = false
#You can customize which block produces wind.
#Write each blockstate to one of this format:
#  [block ID]   (Matches all state of the block)
#  [block ID]#[property1=value],[property2=value],[property3=value]   (Matches state of the block that has specified properties)
#Same property cannot be specified multiple times. Wind sources with any invalid part will be excluded.
windSources = ["fire", "campfire#lit=true", "soul_campfire#lit=true"]
#Horizontal movement speed while paragliding.
#Range: 0.2 ~ 10.0
paraglidingSpeed = 1.0
#Durability of Paragliders. Set to zero to disable durability.
#Range: > 0
paragliderDurability = 0

[spiritOrbs]
	#If true, Ender Dragon will drop heart container(stamina vessel if heart container is disabled) upon death.
	enderDragonDropsVessel = false
	#If true, Raids will give heart container(stamina vessel if heart container is disabled) upon victory.
	raidGivesVessel = false

[vessels]
	#Starting health points.
	#Range: 1 ~ 512
	startingHearts = 10
	#Maximum amount of Heart Containers one player can consume.
	#Do note that the maximum health point is capped at 1024 (512 hearts).
	#Range: 0 ~ 512
	maxHeartContainers = 20
	#Maximum amount of stamina Player can get. Do note that one third of this value is equal to one stamina wheel.
	#Range: > 0
	maxStamina = 3000
	#Amount of stamina Player starts with. Values higher than maxStamina doesn't work.
	#If you want to make this value displayed as exactly one stamina wheel, you have to make this value one third of maxStamina.
	#Range: > 0
	startingStamina = 1000
	#Stamina Vessels players need to obtain max out stamina. More vessels means lesser stamina increase per vessel.
	#Range: > 0
	maxStaminaVessels = 10

[stamina]
	#Paragliding and ascending will consume stamina.
	paraglidingConsumesStamina = true
	#Actions other than paragliding or ascending will consume stamina.
	runningAndSwimmingConsumesStamina = false

	[stamina.consumptions]
		#Range: > -2147483648
		idleStaminaConsumption = 20
		#Range: > -2147483648
		midairStaminaConsumption = 0
		#Range: > -2147483648
		runningStaminaConsumption = -10
		#Range: > -2147483648
		swimmingStaminaConsumption = -6
		#Range: > -2147483648
		underwaterStaminaConsumption = 3
		#Range: > -2147483648
		breathingUnderwaterStaminaConsumption = 10
		#Range: > -2147483648
		ridingStaminaConsumption = 20
		#Range: > -2147483648
		paraglidingStaminaConsumption = -3
		#Range: > -2147483648
		ascendingStaminaConsumption = -3

