
#Common configurations for Abundance
[common]

	#Values for biome frequencies; lower = more rare. (Requires restart)
	[common.biome_weights]
		"Nemophila Fields weight" = 3
		"Lavender Fields weight" = 3
		"Lavender Forest weight" = 2

