
[tweaks]

	[tweaks.sweet_berries]
		#If Sweet Berry Bushes require pips to place, to prevent accidental placement
		"Berries require pips" = true

[items]

	[items.music_disc_fox]
		#The chance that a Fox has to spawn with a Fox music disc
		"Fox music disc chance" = 0.01
		#If Foxes can spawn with a Fox music disc
		"Enable Fox music disc" = true

