defaultUncompletedIconColor = "#FFFFFF"
defaultUncompletedTitleColor = "#0489C1"
defaultCompletedIconColor = "#50DB13"
defaultCompletedTitleColor = "#50DB13"
doAdvancementsBackgroundFade = false
showDebugCoordinates = false
orderTabsAlphabetically = true
#Values below 50% might give odd results, use on own risk ;)
#Range: 1 ~ 100
uiScaling = 100
#Lists the criteria for partially completed advancements, e.g. the biomes required for 'Adventuring Time'
#    Off: Vanilla default
#    Default: List which criteria you have already obtained
#    Spoiler: Only reveal unobtained criteria
#    All: Show both obtained and unobtained criteria
criteriaDetail = "Spoiler"
criteriaDetailRequiresShift = true
addInventoryButton = false
defaultDrawDirectLines = false
defaultHideLines = false
defaultCompletedLineColor = "#FFFFFF"
defaultUncompletedLineColor = "#FFFFFF"

