#modifies the size of the leaves
#Range: 1 ~ 20
leafSize = 4
#modifies how long it takes for the leaves to disappear
#Range: 100 ~ 2000
leafLifespan = 200
#modifies the amount of leaves that are spawning
#Range: 0 ~ 10000
leafSpawnRate = 10
#modifier the amount of leaves are spawning from conifer trees
#Range: 0 ~ 10000
coniferLeafSpawnRate = 2
#weather player placed blocks should also drop leaves
dropFromPlayerPlacedBlocks = true
#how much room below the leaves block is needed for the leaves to spawn
#Range: 1 ~ 20
minimumFreeSpaceBelow = 1

