#Draw a black box behind effect icons
effect_box = true
#A list of effects that should not be registered nor shown on JEI
hidden_effects = ["alexsmobs:bug_pheromones", "alexsmobs:clinging", "alexsmobs:debilitating_sting", "alexsmobs:exsanguination", "alexsmobs:fear", "alexsmobs:oiled", "alexsmobs:poison_resistance", "alexsmobs:tigers_blessing", "seasonals:fall_flavor"]

