#Range: 1 ~ 1001
netherPyramidMaxChunkDistance = 1001
#
# Average distance between spawn attempts for Repurposed Structures Pyramids.
# 1 for spawning in most chunks and 1001 for none.
#Range: 1 ~ 1001
badlandsPyramidMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidSnowyMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidEndMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidIcyMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidJungleMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidMushroomMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidOceanMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidGiantTreeTaigaMaxChunkDistance = 1001
#Range: 1 ~ 1001
pyramidFlowerForestMaxChunkDistance = 1001

